### ISSUE TITLE
Persist Login

### ISSUE THREAD

**Issue by stoutZero** [jackrobertscott/forge#4]
I have to re-login every time I quit & reopened the app on mac.
I haven't tried rebooting my mac, but I'm pretty sure it's gonna be the same case.

**Comment by outenki** [comment]
Same issue here.

**Comment by jackrobertscott** [comment]
For some reason, the following code prevents this in dev mode *but* doesn't work in production:

```js
app.on('window-all-closed', event => {
  event.preventDefault();
});
```

See: http://simurai.com/electron.atom.io/docs/all/#event-window-all-closed

I will endeavour to fix this as soon possible!

**Comment by jackrobertscott** [comment]
This should be fixed now i.e. version 0.3.1 👍 

```js
window.on('close', event => {
  if (window) {
    event.preventDefault();
    window.hide();
  }
});
```

The window will now hide instead of destroying.
