### ISSUE TITLE
Download links are broken on the website

### ISSUE THREAD

**Issue by orenreu** [jackrobertscott/forge#7]

**Comment by yuwanlin** [comment]
> _No description provided._

download it from release version.

**Comment by jackrobertscott** [comment]
The website uses the GitHub api to fetch the latest release to download - but the requests have a limit to the number of times they can be fetched within a given time. Too many requests result in the download links breaking.

I have update the links now so they should take you to the correct "releases" page when the fetch queries exceed the limits and fail. 👍
